### PR TITLE
Feat/map: Filter Page and Layout Update(booths, routes and symbol points)

### PR DESCRIPTION
**Pull request by AmiyaSX**
- Finish layout(**booths**, **routes** and **points**) for floor 2, 3 in Nymble. Align design with figma.
img_v3_02fu_cd38eed8-6538-4a48-ba1a-d387eead0a8g
img_v3_02fu_a1d4ac78-c7e6-45ce-9340-001531037bdg

- Implement filter page for highlighting booths later (local storage). Align design with figma.
img_v3_02fu_9401aab2-005b-4129-9c92-becfbafbf79g
img_v3_02fu_9209758f-7a02-4b03-aae9-1d16971dfd3g
img_v3_02fu_51aeb7cf-265f-4dab-9950-ff389a9981ag

### CODE REVIEW

**Review by hampfh — COMMENTED** [review]
This is really cool! Good job this is awesome!

Overall I think everything works great I just want to discuss a few things:
* There seem to be a bug with the selection of booths (see video)

https://github.com/user-attachments/assets/f8aa6de1-2c53-43e1-8ac4-1a87ca84a032
* It it possible to make the logos a little smaller (right now I feel like they are overflowing quite a lot) (maybe even possible to introduce clustering?)
* Is it possible to increase the max zoom, you can't zoom in very far right now
* Filter button overlaps search
CleanShot 2024-10-24 at 09 13 37
* Maybe it's just for me? But I can't scroll in this dropdown, can you? I have to drag the thumb at the right side
CleanShot 2024-10-24 at 09 14 34

**Comment by hampfh** [comment]
I also noticed that the page crashed if we couldn't find the exhibitor, that might be worth fixing, maybe we just exclude that exhibitor instead? What do you think?

**Comment by AmiyaSX** [comment]
Hi I fixed most of the problems you mentioned above. @hampfh 
For the filter icon overlapping with the search bar, we will refactor the sidebar(probably remove it and only keep a search input box there) so the filter icon will be that place, but right now I moved it to the right.

Also I didn't see the page crash when I try to search the exhibitor that is not exit (maybe provide a example that I can test?)

**Review by hampfh — APPROVED** [review]
Great! 🥳

**Pull request merged**
